server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /monitor
spring:
  datasource:
    url: jdbc:mysql:///mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml